In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp
from scipy import stats
from pathlib import Path
from collections import Counter

In [2]:
# Connecting the database

# Allows user input for the Postgres pass, so it doesn't need to be stored in another file
dbpass = input("Type password: ")

db_string = f"postgresql://postgres:{dbpass}@127.0.0.1:5432/Group6"
engine = create_engine(db_string)

movies_clean_df.to_sql(name='Movies', con=engine)
raw_oscars_df.to_sql(name='Oscars', con=engine)

,budget,original_title,popularity,release_date,revenue,runtime,status,title,vote_average,vote_count,winner,genres,nominated
0,30000000,Toy Story,21.946943,10/30/1995,373554033.0,81.0,Released,Toy Story,7.7,5415.0,0,Animation,1
1,65000000,Jumanji,17.015539,12/15/1995,262797249.0,104.0,Released,Jumanji,6.9,2413.0,0,Adventure,0
2,0,Grumpier Old Men,11.712900,12/22/1995,0.0,101.0,Released,Grumpier Old Men,6.5,92.0,0,Romance,0
3,16000000,Waiting to Exhale,3.859495,12/22/1995,81452156.0,127.0,Released,Waiting to Exhale,6.1,34.0,0,Comedy,0
4,0,Father of the Bride Part II,8.387519,2/10/1995,76578911.0,106.0,Released,Father of the Bride Part II,5.7,173.0,0,Comedy,0
5,60000000,Heat,17.924927,12/15/1995,187436818.0,170.0,Released,Heat,7.7,1886.0,0,Action,0
6,58000000,Sabrina,6.677277,12/15/1995,0.0,127.0,Released,Sabrina,6.2,141.0,0,Comedy,1
7,0,Tom and Huck,2.561161,12/22/1995,0.0,97.0,Released,Tom and Huck,5.4,45.0,0,Action,0
8,35000000,Sudden Death,5.231580,12/22/1995,64350171.0,106.0,Released,Sudden Death,5.5,174.0,0,Action,0
9,58000000,GoldenEye,14.686036,11/16/1995,352194034.0,130.0,Released,GoldenEye,6.6,1194.0,0,Adventure,0

In [ ]:
# dropping unecessary dependent variables and columns  
X = df.drop(columns=["popularity", "status", "release_date","vote_average", "vote_count", "original_title", "nominated"])

#create dummy columnn
obj_columns = ["genres"]
X = pd.get_dummies(X, obj_columns)

In [ ]:
y = df["nominated"].to_frame()